## YAML Template.
---

kind: Service
apiVersion: v1
metadata:
  name: sl-test
spec:
  type: NodePort
  selector:
    app: sl-test
  ports:
  - name: http
    protocol: TCP
    port: 8088
    targetPort: 8080
    nodePort: 31008

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sl-test
  labels:
    app: sl-test
    environment: local
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: sl-test
  template:
    metadata:
      labels:
        app: sl-test
    spec:
      containers:
      - name: sl-test
        image: local-docker-repo:5000/sl-test:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
